### ISSUE TITLE
Parse encyc-rg content out of articles in encyc-front

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/encyc-core#1]
The backend editors' mediawiki is being used to author content for both the public encyclopedia (encyclopedia.densho.org) and the new educational resource guide (RG). Articles authored through the editors' mediawiki will appear in both sites; however, certain content components (e.g., databoxes) should appear only in the RG. These elements will be wrapped in a particular `<span>` class:

`<span class="rgonly"></span>`

encyc-core should remove all html content within these spans prior to pushing the article to the encyc-front ES index.

**Comment by gjost** [comment]
Fixed in `encyc-rg` 57e2810.
