### ISSUE TITLE
RG links marked with the "notrg" class

### ISSUE THREAD

**Issue by gjost** [denshoproject/encyc-core#10]
There are intra-encyclopedia/rg links to articles that appear in the RG, that are erroneously marked with the "notrg" class, causing them to look like links back to the encyclopedia article.

For example, the RG entry for, "Baseball Saved Us" (http://rgstage.densho.org/wiki/Baseball%20Saved%20Us%20(book)/) has links in the "for more info" section ("might also like") to, "The Bracelet" and "Fish for Jimmy". The url for "The Bracelet" is:

http://encyclopedia.densho.org/The%20Bracelet%20(book)/

And the a tag is classed: 'encyc notrg'. But this article *does* appear in the RG:

http://rgstage.densho.org/wiki/Baseball%20Saved%20Us%20(book)/

Looks like the code that is re-writing the urls isn't doing what we thought...

**Comment by gjost** [comment]
This was a complicated beast.

In `encyc-core`, `models.legacy.wikipage.mark_offsite_encyc_rg_links` rewrote links to the main encyclopedia with the encycfront domain, adding the protocol ('http://') and domain.  When the function was run subsequently, these links were understood by the function to be offsite links, the markers were removed, and subsequent passes would fail to mark links properly.
Furthermore, `encyc-core` has to have a list of RG articles in order to flag articles as part of the RG. This requires `encyc articles` to be run at least twice (first pass indexes all the articles, second pass has the list and can identify RG articles).  This important fact was known but was forgotten by your humble writer.

Fix:
`encyc-core` now *marks* links as `rg`/`notrg` but no longer modifies the links themselves.
`encyc-rg` examines page links and inserts the protocol and domain for `encyc-front`.
`encyc-core`: If no RG articles are detected, reminds users to run `encyc articles --force` again.

Other fixes:

`encyc-core` and `encyc-rg` now have config properties to enable or disable HTTPS for easier development/testing (a previous commit made links use HTTPS).

**Comment by GeoffFroh** [comment]
This bug has apparently re-emerged.

**Comment by GeoffFroh** [comment]
Note that the current functionality may differ from the 2/15/2018 comment above. It appears that the `rg` / `notrg` classes are added to the article doc for ES in the `wikipage.py` model at 
https://github.com/denshoproject/encyc-core/blob/master/encyc/models/wikipage.py#L191

Might be an issue with the data in `rg_titles` list?

**Comment by gjost** [comment]
Partial fix on the `encyc-core` side in commits `84c1707` and `4506d3c` which update the RG API URL (a version bump) and make the function fail loudly.  These issues were preventing `encyc-core` from properly generating the list of RG titles.

The "Might also..." section text now appears in Elasticsearch with the correct `rg` link classes but is not being displayed in the web UI.  Working on that in `encyc-rg`.

**Comment by gjost** [comment]
The other part of the fix in `encyc-rg` commit `7997650` for package `encycrg-master_3.3.1~deb10`.
