### ISSUE TITLE
Mark articles as RG-only

### ISSUE THREAD

**Issue by gjost** [denshoproject/encyc-core#11]
Editors would like to be able to mark certain articles in the editors' mediawiki that should appear *only* in the RG, and *not* in the regular encyclopedia. Currently, we identify articles that appear in the RG (and *also* in encyc-front) by placing the databox-RGCore databox in the article itself. 

Is encyc-front/core set up so that we could have the indexer detect an "rgonly" tag? We could have a simple mediawiki template (akin to the workflow templates) that inserts a specially-classed (or id'ed) div for encyc-front/core to look for.

**Comment by gjost** [comment]
We'll do this after launch.

**Comment by GeoffFroh** [comment]
MW pages that are intended for the RG only (and not encyc-front) are marked with the template tag, `https://editors.densho.org/wiki/Template:publish-rgonly`

The tag inserts a <div> into the mw article html:

`<div class="alert nopublish-encycfront encyc-remove">...</div>`

The class, `nopublish-encycfront` can be used to identify that the page is intended for the RG only. (The class, `encyc-remove` can also be used to indicate that the html element and children should be removed from the html string prior to indexing.)

**Comment by gjost** [comment]
As of commit `936db4a`,  `encyc-core` is feeding both the `published_rg` and `published_encyc` fields.
`encycrg` is now using `published_rg` as of commit `1bc648c`.
