### ISSUE TITLE
Implement support for mwclient (replaces wikitools library)

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/encyc-core#27]
`encyc-core` currently uses wikitools which is not fully supported for python3. It would be better to move to mwclient however, the module appears not to be compatible with the version of MediaWiki we are running (MW 1.24).

In addition, MW 1.24 is already EOL; we should be on 1.31.

We need to investigate potential incompatibilities with our codebase(s).

related to: https://github.com/densho/encyc-psms/issues/15

**Comment by gjost** [comment]
Upgraded to MediaWiki 1.27 LTS in  `encyc-mw` dev branch commit `19d05995`.

**Comment by GeoffFroh** [comment]
This relates to MW LTS upgrade https://github.com/denshoproject/encyc-mw/issues/2
