### ISSUE TITLE
encyc-rg content not being parsed from production encyclopedia

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/encyc-core#3]
Content is not being removed from the front-end public encyclopedia as per functionality in  https://github.com/densho/encyc-core/issues/1

The designated content is properly specified in the core config file:

https://github.com/densho/encyc-core/blob/master/conf/core.cfg#L53

However, it appears in the production encyclopedia. See:

http://encyclopedia.densho.org/Caught_in_Between%3A_What_to_Call_Home_in_Times_of_War_%28film%29/

The production mediawiki/encyc-core VM (fuzzy) is running the latest version of encyc-core on master and the config file appears to be valid.

**Comment by gjost** [comment]
All the configs and other setup were as they were supposed to be.  Problem was that the value of `config.DOCSTORE_INDEX` was not properly maintained along the chain from `cli.articles` to the place where it was supposed to be used to determine the list of divs to remove from article text.
